myshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('',views.cart_detail,name="cart_detail"),
    path('add/<int:product_id>/',views.cart_add,name="cart_add"),
    path('remove/<int:product_id>/',views.cart_remove,name="cart_remove"),
]

myshop/coupons/urls.py
from django.urls import path

from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/',views.coupon_apply,name='apply'),
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls',namespace='cart')),
    path('orders/',include('orders.urls',namespace='orders')),
    path('zarinpal/',include('zarinpal.urls',namespace='zarinpal')),
    path('coupons/',include('coupons.urls',namespace='coupons')),
    path('rosetta/',include('rosetta.urls')),
    path('', include("shop.urls",namespace="shop")),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myshop/orders/urls.py
from django.urls import path
from . import views

app_name="orders"

urlpatterns = [
    path('create/',views.order_create,name='order_create'),
    path("admin/order/<int:order_id>/",views.admin_order_detail,name="admin_order_detail"),
    path("admin/order/<int:order_id>/pdf/",views.admin_order_pdf,name="admin_order_pdf"), 
]

myshop/shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path("",views.product_list,name="product_list"),
    path("<slug:category_slug>/",views.product_list,name="product_list_by_category"),
    path("<int:id>/<slug:slug>/",views.product_detail,name="product_detail"),
    
]

myshop/cart/models.py
from django.db import models

# Create your models here.

myshop/cart/forms.py
from django import forms
from django.utils.translation import override

PRODUCT_QUANTITY_CHOICES = [(i,str(i)) for i in range (1,21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
    override = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

myshop/cart/views.py
from django.shortcuts import render , get_object_or_404 , redirect
from django.views.decorators.http import require_POST
from .cart import Cart
from shop.models import Product
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm

# Create your views here.


@require_POST
def cart_add(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Product,id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,quantity=cd['quantity'],override_quantity=cd['override'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Product,id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    coupon_apply_form = CouponApplyForm()
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity':item["quantity"],
            "override":True
        })
    return render(request,'cart/detail.html',{'cart':cart,"form":coupon_apply_form})

myshop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}

{% block title %}
  Shopping Cart
{% endblock title %}


{% block content %}
<div class="container mt-4">
    <h1>Your Shopping Cart</h1>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Image</th>
                    <th scope="col">Product</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Unit Price</th>
                    <th scope="col">Total</th>
                    <th scope="col">Remove</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                    {% with product=item.product %}
                        <tr>
                            <td>
                                <a href="{{product.get_absolute_url}}">
                                    <img class="img-thumbnail" src="{{product.image.url}}" alt="{{product.name}}" width="100" height="100">
                                </a>
                            </td>
                            <td>
                                <a href="{{product.get_absolute_url}}" class="text-decoration-none">{{product.name}}</a>
                            </td>
                            <td>
                                <form action="{% url 'cart:cart_add' product.id %}" method="POST">
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.override }}
                                    <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-refresh"></i> Update</button>
                                    {% csrf_token %}
                                </form>
                            </td>
                            <td>${{ item.product.price }}</td>
                            <td>${{ item.total_price }}</td>
                            <td>
                                <form action="{% url 'cart:cart_remove' product.id %}" method="POST">
                                    <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></button>
                                    {% csrf_token %}
                                </form>
                            </td>
                        </tr>
                    {% endwith %}
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="row justify-content-end">
        <div class="col-md-4">
            <table class="table">
                <tbody>
                    <tr>
                        <th>Total</th>
                        <td class="text-right">${{ cart.get_total_price }}</td>
                    </tr>
                    {% if cart.coupon %}
                        <tr>
                            <th>Subtotal ({{ cart.coupon.discount }}% Off)</th>
                            <td class="text-success text-right">${{ cart.get_total_price_after_discount }}</td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
            <p>
                <a href="{% url 'shop:product_list' %}" class="btn btn-primary btn-block">Continue Shopping</a>
                <a href="{% url 'orders:order_create' %}" class="btn btn-success btn-block">Checkout</a>
            </p>
        </div>
    </div>
</div>
<div class="container mt-4 mb-4">
    <div class="card">
        <div class="card-body">
            <h3 class="card-title">Apply Coupon Code</h3>
            <form action="{% url 'coupons:apply' %}" method="POST">
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Apply</button>
                {% csrf_token %}
            </form>
        </div>
    </div>
</div>
{% endblock content %}