myshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('',views.cart_detail,name="cart_detail"),
    path('add/<int:product_id>/',views.cart_add,name="cart_add"),
    path('remove/<int:product_id>/',views.cart_remove,name="cart_remove"),
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls',namespace='cart')),
    path('orders/',include('orders.urls',namespace='orders')),
    path('zarinpal/',include('zarinpal.urls',namespace='zarinpal')),
    path('coupons/',include('coupons.urls',namespace='coupons')),
    path('rosetta/',include('rosetta.urls')),
    path('', include("shop.urls",namespace="shop")),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myshop/orders/urls.py
from django.urls import path
from . import views

app_name="orders"

urlpatterns = [
    path('create/',views.order_create,name='order_create'),
    path("admin/order/<int:order_id>/",views.admin_order_detail,name="admin_order_detail"),
    path("admin/order/<int:order_id>/pdf/",views.admin_order_pdf,name="admin_order_pdf"), 
]

myshop/shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path("",views.product_list,name="product_list"),
    path("<slug:category_slug>/",views.product_list,name="product_list_by_category"),
    path("<int:id>/<slug:slug>/",views.product_detail,name="product_detail"),
    
]

myshop/orders/models.py
from django.db import models
from shop.models import Product
# Create your models here.

class Order(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    address = models.TextField()
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    
    class Meta:
        ordering = ('-created',)
    
    def __str__(self):
        return f'Order {self.id}'
    
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())
    

class OrderItem(models.Model):
    order = models.ForeignKey(Order,related_name='items',on_delete=models.CASCADE)
    product = models.ForeignKey(Product,related_name='order_items',on_delete=models.CASCADE)
    price = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField(default=1)
    
    def __str__(self):
        return str(self.id)
    
    def get_cost(self):
        return self.price * self.quantity
        

myshop/orders/forms.py
from django import forms
from django.forms import fields
from .models import Order

class OrderCreateform(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name',"last_name","email",'address','postal_code','city']
        

myshop/orders/views.py
from django.shortcuts import render , redirect , get_object_or_404
from .forms import OrderCreateform
from .models import OrderItem , Order
from cart.cart import Cart
from django.urls import reverse
from django.contrib.admin.views.decorators import staff_member_required
import weasyprint
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import render_to_string
from .tasks import send_order_email
from shop.recommender import Recommender
# Create your views here.

def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateform(request.POST)
        if form.is_valid():
            order = form.save()
            
            # This list contains all the products in the cart,
            # which we store in Redis by calling the products_bought function.
            product_list_for_redis=[]
            
            for item in cart:
                OrderItem.objects.create(order=order,product=item['product'],price=item['price'],quantity=item['quantity'])
                product_list_for_redis.append(item['product'])
            
            r = Recommender()
            # store in redis
            r.products_bought(product_list_for_redis)
              
            cart.clear()
            #order_created.delay(order.id)
            #return render(request,'orders/order/created.html',{'order':order})
            request.session['order_id'] = order.id
            return redirect(reverse('zarinpal:request'))
        
    else:
        form = OrderCreateform()
    return render(request,'orders/order/create.html',{"form":form,"cart":cart})



@staff_member_required
def admin_order_detail(request,order_id):
    order = get_object_or_404(Order,id=order_id)
    return render(request,"admin/orders/order/detail.html",{"order":order})



@staff_member_required
def admin_order_pdf(request,order_id):
    order = get_object_or_404(Order,id=order_id)
    html = render_to_string('orders/order/pdf.html',{"order":order})
    response = HttpResponse(content_type='application/pdf')
    response["Content-Disposition"] = f'filename=order_{order.id}.pdf'
    weasyprint.HTML(string=html).write_pdf(response,stylesheets=[weasyprint.CSS(
        settings.STATIC_ROOT + 'css/pdf.css'
    )])
    return response

myshop/orders/templates/orders/order/create.html
{% extends 'shop/base.html' %}


{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 m-4">
            <div class="card shadow-lg p-4">
                <h1 class="mt-2 mb-4">Checkout</h1>
                <ul class="list-group mb-4">
                    {% for item in cart %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <div class="media">
                            <img src="{{item.product.image.url}}" class="mr-3 rounded-circle img-thumbnail" height="60" width="60" alt="">
                            <div class="media-body">
                                <h5 class="mt-0">{{item.product.name}}</h5>
                                {{item.price}}
                                <span class="badge badge-primary badge-pill">{{item.quantity}}</span>
                            </div>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
                <div class="col-md-4">
                    <table class="table">
                        <tbody>
                            <tr>
                                <th>Total</th>
                                <td class="text-right">${{ cart.get_total_price }}</td>
                            </tr>
                            {% if cart.coupon %}
                                <tr>
                                    <th>Subtotal ({{ cart.coupon.discount }}% Off)</th>
                                    <td class="text-success text-right">${{ cart.get_total_price_after_discount }}</td>
                                </tr>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="id_first_name">First Name</label>
                            <input type="text" class="form-control" name="first_name" maxlength="100" required id="id_first_name">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="id_last_name">Last Name</label>
                            <input type="text" class="form-control" name="last_name" maxlength="100" required id="id_last_name">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_email">Email</label>
                        <input type="email" class="form-control" name="email" maxlength="254" required id="id_email">
                    </div>
                    <div class="form-group">
                        <label for="id_address">Address</label>
                        <textarea name="address" class="form-control" cols="40" rows="4" required id="id_address"></textarea>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="id_postal_code">Postal Code</label>
                            <input type="text" name="postal_code" maxlength="20" class="form-control" required id="id_postal_code">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="id_city">City</label>
                            <input type="text" class="form-control" name="city" maxlength="100" required id="id_city">
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary btn-block mt-4">Place Your Order</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

myshop/orders/templates/orders/order/created.html
{% extends 'shop/base.html' %}

{% block content %}

<div class="container mt-5">
    <div class="card shadow p-4">
        <h4 class="text-center mb-4">Thank you for your order!</h4>
        <p class="text-center">Your order has been successfully placed. Your shipping ID is <strong>{{ order.id }}</strong>.</p>
        <div class="text-center">
            <a href="{% url 'shop:product_list' %}" class="btn btn-primary mt-3">Continue Shopping</a>
        </div>
    </div>
</div>
{% endblock content %}

myshop/orders/templates/orders/order/pdf.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Invoice</title>
    <link rel="stylesheet" type="text/css" href={% static 'css/pdf.css' %}>
</head>
<body>
    <div class="invoice-container">
        <div class="invoice-header">
            <h1 class="name">Myshop</h1>
        </div>

        <div class="invoice-meta">
            <p>Invoice no {{order.id}}</p>
            <p><small>{{order.created|date:"M d Y"}}</small></p>
        </div>

        <div class="bill-to">
            <h3>Bill to</h3>
            <p>Recipient: {{order.first_name}} {{order.last_name}}</p>
            <p>Email: {{order.email}}</p>
            <p>Shipping Address: {{order.address}}</p>
            <p>Postal Code: {{order.postal_code}}</p>
        </div>

        <h3>Items Bought</h3>
        <table class="items-table">
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Cost</th>
                </tr>
            </thead>
            <tbody>
                {% for item in order.items.all  %}
                    <tr>
                        <td>{{item.product.name}}</td>
                        <td>{{item.price}}</td>
                        <td>{{item.quantity}}</td>
                        <td>{{item.get_cost}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="status">
            {% if order.paid %}
                <span class="text-green">Paid</span>
            {% else %}
                <span class="text-yellow">Pending Payment</span>
            {% endif %}
        </div>
    </div>
</body>
</html>