myshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('',views.cart_detail,name="cart_detail"),
    path('add/<int:product_id>/',views.cart_add,name="cart_add"),
    path('remove/<int:product_id>/',views.cart_remove,name="cart_remove"),
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls',namespace='cart')),
    path('orders/',include('orders.urls',namespace='orders')),
    path('zarinpal/',include('zarinpal.urls',namespace='zarinpal')),
    path('coupons/',include('coupons.urls',namespace='coupons')),
    path('rosetta/',include('rosetta.urls')),
    path('', include("shop.urls",namespace="shop")),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path("",views.product_list,name="product_list"),
    path("<slug:category_slug>/",views.product_list,name="product_list_by_category"),
    path("<int:id>/<slug:slug>/",views.product_detail,name="product_detail"),
    
]

myshop/shop/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

# Create your models here.


class Category(models.Model):
    name = models.CharField(_("name"),max_length=200,db_index=True)
    slug = models.SlugField(_("slug"),max_length=200,db_index=True)
    
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])
    
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        
        
    def __str__(self):
        return self.name
    
    

class Product(models.Model):
    category = models.ForeignKey(Category,related_name="products" ,on_delete=models.CASCADE,)
    name = models.CharField(_("name"),max_length=200,db_index=True)
    slug = models.SlugField(_("slug"),max_length=200,db_index=True)
    image = models.ImageField(_("image"),upload_to='products/%Y/%m/%d', blank =True)
    description = models.TextField(_("description"),blank =True)
    price = models.PositiveIntegerField(_("price"))
    available = models.BooleanField(_("available"),default=True)
    created = models.DateField(_("created"),auto_now_add=True)
    updated = models.DateField(_("updated"),auto_now=True)
    
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id,self.slug])
    
    class Meta:
        ordering = ('name',)
        index_together = (('id','slug'),)
        
    def __str__(self):
        return self.name    
        
    
        

myshop/shop/views.py
from itertools import product
from django.shortcuts import render,get_object_or_404
from .models import Category,Product
from cart.forms import CartAddProductForm
from .recommender import Recommender

# Create your views here.


def product_list(request,category_slug=None):
    
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    
    cart_product_form = CartAddProductForm()
    
    if category_slug:
        category = get_object_or_404(Category,slug=category_slug)
        products = Product.objects.filter(category=category,available=True)
        
    context = {
        'categories':categories,
        'category':category,
        'products':products,
        'form':cart_product_form,
    }
    
    return render(request,'shop/product/list.html',context)
    
    
def product_detail(request,id,slug):
    
    product = get_object_or_404(Product,id=id,slug=slug,available=True)
    category = product.category
    cart_product_form = CartAddProductForm()
    
    try:
        r = Recommender()
        recommended_products = r.suggest_products_for([product],2)
        context={
        'product':product,
        'category':category,
        'form':cart_product_form,
        'recommended_products':recommended_products,
    }
    except:
        context={
        'product':product,
        'category':category,
        'form':cart_product_form,
    }    
    
    return render(request,'shop/product/detail.html',context)        

myshop/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
    <title>
        {% block title %}
            
        {% endblock title %}        
    </title>
</head>
<body>
    <!-- header -->
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'shop:product_list' %}">My Store</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href="{% url 'shop:product_list' %}">Home <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link active" href="{% url 'cart:cart_detail' %}">
            <i class="fa fa-shopping-cart"></i>
            
            {% if request.session.cart %}
              <span class="badge badge-primary">{{cart|length}}</span> <span class="sr-only">(current)</span>
              <span>total price : {{cart.get_total_price}}</span>
            {% endif %}
              
          </a>
        </div>
      </div>
    </nav>
  {% block content %}
      
  {% endblock content %}
        
</body>
</html>